[project]
name = "wrfrontiers-exporter"
version = "1.0.0"

[tool.optionsconfig]
schema_module = "options_schema"
env_example_path = ".env.example"
readme_path = "README.md"
log_file = "logs/optionsconfig.log"